### PR TITLE
39 test cases for dbt automation

### PR DESCRIPTION
**Pull request by fatchat**

### CODE REVIEW

**Comment by Ishankoradia** [comment]
Have written tests cases for the utility functions except warehousec clients.

Will then write test cases for each operation along with running the dbt code and checking the output at the warehouse.

**Comment by fatchat** [comment]
`check_call` when running commands via `subprocess`

**Comment by fatchat** [comment]
when you run a command which generates a file and you are testing for the existence of the file after, make sure the file doesn't exist beforehand. when this runs on github it won't be there but when we run locally we may have stuff left over from previous runs

**Comment by Ishankoradia** [comment]
> when this runs on github it won't be there

It will not be there for sure. For each test run locally pytest creates a new temp directory (`tmpdir` fixture that i am using). Everything starts from fresh everytime we run `pytest`

**Review by Ishankoradia — APPROVED** [review]

**Pull request merged**
